name: openvino-sdk
base: core18
version: '2020.2.120'
summary: Intel's OpenVINO Toolkit
description: |
  SDK to build OpenVINO applications

grade: devel
confinement: strict

parts:
  cmake:
    source: https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2.tar.gz
    plugin: nil
    override-build: |
      ./bootstrap
      make -j4
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
      make install DESTDIR=/
    build-packages:
      - build-essential
      - libssl-dev
  openvino:
    source: git://github.com/openvinotoolkit/openvino
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DPYTHON_EXECUTABLE=/usr/bin/python3.6
    build-environment:
      - OpenCV_DIR: $SNAPCRAFT_STAGE/usr
      - PATH: /usr/lib/ccache:$PATH
    build-packages:
      - ccache
      - autoconf
      - automake
      - bison
      - libavcodec-dev
      - libavformat-dev
      - libgtk2.0-dev
      - libswscale-dev
      - libtool
      - libusb-1.0-0-dev
      - pkg-config
      - python3-dev
      - python3-pip
      - wget
    override-build: |
       cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DPYTHON_EXECUTABLE=/usr/bin/python3.6 $SNAPCRAFT_PART_SRC
       make -j4
       make DESTDIR=$SNAPCRAFT_PART_INSTALL install
    after: [opencv, cmake]
  opencv:
    source: git://github.com/opencv/opencv
    plugin: cmake
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTS=OFF
      - -DINSTALL_PYTHON_EXAMPLES=OFF
      - -DOPENCV_ENABLE_NONFREE=ON
      - -DCMAKE_SHARED_LINKER_FLAGS=-latomic
      - -DBUILD_EXAMPLES=OFF
    build-packages:
      - build-essential
      - cmake
      - libavcodec-dev
      - libavformat-dev
      - libdc1394-22-dev
      - libgtk2.0-dev
      - libjpeg-dev      
      - libpng-dev
      - libswscale-dev
      - libtbb-dev
      - libtiff-dev
      - pkg-config
      - python3-dev
    stage-packages:
      - libatk1.0-0
      - libavcodec57
      - libavformat57
      - libavutil55
      - libbluray2
      - libchromaprint1
      - libdc1394-22
      - libdrm2
      - libgme0
      - libgomp1
      - libgsm1
      - libgtk2.0-0
      - libmp3lame0
      - libmpg123-0
      - libnuma1
      - libogg0
      - libopenjp2-7
      - libopenmpt0
      - libopus0
      - libraw1394-11
      - libshine3
      - libsnappy1v5
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswresample2
      - libswscale4
      - libtheora0
      - libtwolame0
      - libusb-1.0-0
      - libva-drm2
      - libva-x11-2
      - libva2
      - libvdpau1
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libvpx5
      - libwavpack1
      - libwebp6
      - libwebpmux3
      - libx264-152
      - libx265-146
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxvidcore4
      - libzvbi0
