name: openvino-example
base: core20
version: 'git'
summary: Intel's OpenVINO Toolkit example
description: |
  Example for OpenVINO snaps.

grade: devel
confinement: strict

parts:
  opencv:
    source: git://github.com/opencv/opencv
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTS=OFF
      - -DINSTALL_PYTHON_EXAMPLES=ON
      - -DOPENCV_ENABLE_NONFREE=ON
      - -DCMAKE_SHARED_LINKER_FLAGS=-latomic
      - -DBUILD_EXAMPLES=ON
#      - -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules
    build-packages:
      - build-essential
      - pkg-config
      - python3-dev
      - python3-numpy
      - python3-pip
      - libhdf5-103
      - libhdf5-dev
      - libatlas-base-dev
      - liblapacke-dev
      - gfortran
      - libjpeg-dev
      - libtiff-dev
      - libopenjp2-7-dev
      - libpng-dev
      - libwebp-dev
      - libopenexr-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libdc1394-22-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
    stage-packages:
      - python3-numpy
      - python3-pip
      - libhdf5-103
      - gfortran
    override-build: |
       cmake $SNAPCRAFT_PART_SRC -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=OFF -DINSTALL_PYTHON_EXAMPLES=ON -DOPENCV_ENABLE_NONFREE=ON -DCMAKE_SHARED_LINKER_FLAGS=-latomic -DBUILD_EXAMPLES=ON
       make -j4
       make DESTDIR=$SNAPCRAFT_PART_INSTALL install
#      if [ ! -d opencv_contrib ]; then
#        git clone https://github.com/opencv/opencv_contrib.git
#      else
#        cd opencv_contrib
#        git pull
#        cd ...
#      fi
