name: openvino-samples
base: core18
version: '2020.3.194'
summary: Intel's OpenVINO Toolkit samples
description: |
  Sample applications in OpenVINO.

grade: devel
confinement: strict

apps:
  benchmark-app:
    command: bin/benchmark_app
    extensions: [openvino-2020-3]

parts:
  openvino:
    source: git://github.com/openvinotoolkit/openvino
    source-subdir: inference-engine/samples
    source-branch: 2020.3.0
    plugin: cmake    
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DPYTHON_EXECUTABLE=/usr/bin/python3.6
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -rv inference-engine/samples/*/Release/* $SNAPCRAFT_PART_INSTALL/bin
    stage-packages:
      - libjbig0
      - libjpeg-turbo8
      - libpng16-16
      - libtiff5
