name: openvino-core20-example
base: core20
version: 'git'
summary: Intel's OpenVINO Toolkit example
description: |
  Example for OpenVINO snaps.

grade: devel
confinement: strict

parts:
  opencv:
    source: git://github.com/opencv/opencv
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RELEASE
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTS=OFF
      - -DINSTALL_PYTHON_EXAMPLES=ON
      - -DOPENCV_ENABLE_NONFREE=ON
      - -DCMAKE_SHARED_LINKER_FLAGS=-latomic
      - -DBUILD_EXAMPLES=ON
#      - -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules
    build-packages:
      - bison
      - build-essential
      - cmake
      - cpio
      - ffmpeg
      - flex
      - gettext
      - gfortran
      - gobject-introspection
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - iso-codes
      - liba52-0.7.4
      - libaa1
      - libasound2
      - libass9
      - libatlas-base-dev
      - libavc1394-0
      - libavcodec-dev
      - libavformat-dev
      - libbluetooth3
      - libbs2b0
      - libbz2-1.0
      - libcaca0
      - libcap2
      - libcap2-bin
      - libcdparanoia0
      - libchromaprint1
      - libdc1394-22
      - libdc1394-22-dev
      - libdca0
      - libde265-0
      - libdirectfb-1.7-7
      - libdrm-dev
      - libdv4
      - libdvdnav4
      - libfaac0
      - libfdk-aac1
      - libflac8
      - libflite1
      - libfluidsynth-dev
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgirepository-1.0-1
      - libgl1-mesa-dri
      - libgl-dev
      - libgles2
      - libglib2.0-0
      - libgme0
      - libgmp10
      - libgraphene-1.0-0
      - libgsl23
      - libgsm1
      - libgstreamer1.0-0
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgudev-1.0-dev
      - libhdf5-103
      - libhdf5-dev
      - libiec61883-0
      - libjpeg8
      - libjpeg-dev
      - libkate1
      - liblapacke-dev
      - liblcms2-2
      - liblrdf0
      - libmjpegtools-dev
      - libmms0
      - libmodplug1
      - libmp3lame0
      - libmpcdec6
      - libmpeg2-4
      - libmpg123-0
      - libneon27
      - libnettle7
      - libnice10
      - libopenal1
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopenexr-dev
      - libopenjp2-7
      - libopenjp2-7-dev
      - libopenmpt0
      - libopenni2-0
      - libopus0
      - libpango-1.0-0
      - libpng-dev
      - libpulse0
      - libraw1394-11
      - librsvg2-2
      - librtmp1
      - libsbc1
      - libsndfile1
      - libsoundtouch1
      - libsoup2.4-1
      - libspandsp2
      - libspeex1
      - libsrtp2-1
      - libssh2-1
      - libssh-4
      - libswscale-dev
      - libtag-extras1
      - libtheora0
      - libtiff-dev
      - libtwolame0
      - libudev1
      - libusb-dev
      - libv4l-0
      - libv4l-dev
      - libva2
      - libvisual-0.4-0
      - libvo-aacenc0
      - libvo-amrwbenc0
      - libvorbis0a
      - libwavpack1
      - libwebp6
      - libwebp-dev
      - libwebrtc-audio-processing1
      - libwildmidi2
      - libx11-6
      - libx264-dev
      - libxkbcommon0
      - libxrandr2
      - libxv1
      - libxvidcore-dev
      - libzbar0
      - libzvbi0
      - pkg-config
      - python3-dev
      - python3-gi
      - python3-numpy
      - python3-pip
      - python3-scipy
    stage-packages:
      - python3-numpy
      - python3-pip
      - libhdf5-103
      - gfortran
    override-build: |
       export
       unset CPPFLAGS
       unset CFLAGS
       unset CXXFLAGS

       cmake $SNAPCRAFT_PART_SRC -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_TESTS=OFF -DINSTALL_PYTHON_EXAMPLES=ON -DOPENCV_ENABLE_NONFREE=ON -DCMAKE_SHARED_LINKER_FLAGS=-latomic -DBUILD_EXAMPLES=ON
       make -j4
       make DESTDIR=$SNAPCRAFT_PART_INSTALL install
#      if [ ! -d opencv_contrib ]; then
#        git clone https://github.com/opencv/opencv_contrib.git
#      else
#        cd opencv_contrib
#        git pull
#        cd ...
#      fi
